### ISSUE TITLE
Feature's position and value

### ISSUE THREAD

**Issue by XiaoQiSAMA** [zhuxinqimac/PS-SC#2]
By "cvpr21_poster.png", the first image
![image](https://user-images.githubusercontent.com/39402478/170239955-a7c82dbb-2e8f-4dcc-bd2b-7e5fda66ab69.png)
How can I plot this changes?

**Comment by zhuxinqimac** [comment]
Hi Xiaoqi,

You can follow the Generation section in the README, and use the following code to generate traversals. Hope it helps!

```
CUDA_VISIBLE_DEVICES=0 \
    python run_generator_ps_sc.py generate-traversals \
    --network /path/to/xxx.pkl \
    --seeds 0-10 \
    --result-dir /path/to/traversal_results_dir
```

**Comment by XiaoQiSAMA** [comment]
Hi Zhuxinqi, thank you, it's really helpful for me! 
And sorry, I have another question, in my perception, the value of the feature is more like the intensity of the local feature represented by the position of the feature. So, I am confused, why the changes of the value can make image from smile to non-smile? Shouldn't this characteristic be "weaker"?

**Comment by zhuxinqimac** [comment]
This is because non-smile has a very weak (or negative) smile intensity. Smile and non-smile are captured by a single latent dimension as they are reverse of each other.

**Comment by XiaoQiSAMA** [comment]
Thank you! I really learned a lot.
